#!/usr/bin/env python3
"""Experiment 7 - WBS, activity network, CPM and Gantt chart for LabSense.

Single source of truth for the project schedule. Edit TASKS (durations or
predecessors) and re-run; it recomputes the critical path and regenerates:

    exp7-wbs.puml               work breakdown structure
    exp7-activity-network.puml  activity-on-node network with ES/EF/LS/LF/slack
    exp7-gantt.puml             Gantt chart (critical path in red)
    exp7-cpm-table.md           CPM table for the write-up

Usage:  python3 docs/diagrams/exp7_schedule.py
"""

from __future__ import annotations

from datetime import date, timedelta
from pathlib import Path

PROJECT = 'LabSense Mini Project'
START = date(2026, 7, 27)   # Monday of the first week of the semester
TODAY = date(2026, 9, 29)   # status date: tasks finished by now are shown 100 % complete

# Work packages: WBS code, title. Each task below belongs to one.
PHASES = [
    ('1', 'Planning & Requirements'),
    ('2', 'Design'),
    ('3', 'Development'),
    ('4', 'Integration & Testing'),
    ('5', 'Deployment & Closure'),
]

# id, WBS code, task, duration (days), predecessors
TASKS = [
    ('A', '1.1', 'Define problem statement & MVP scope', 3, []),
    ('B', '1.2', 'Gather requirements (PC states, roles, lab rules)', 5, ['A']),
    ('C', '1.3', 'Architecture & tech-stack decisions', 4, ['B']),
    ('D', '2.1', 'Database schema design', 3, ['C']),
    ('E', '2.2', 'Agent-server wire protocol design', 3, ['C']),
    ('F', '2.3', 'UI wireframes & user flows', 4, ['B']),
    ('G', '2.4', 'UML & DFD modelling', 12, ['C']),
    ('H', '3.1', 'Agent: telemetry, D-Bus, sleep inhibitor', 18, ['E']),
    ('I', '3.2', 'Backend: TCP server & PC state manager', 14, ['D', 'E']),
    ('J', '3.3', 'Backend: REST API & JWT RBAC', 10, ['D']),
    ('K', '3.4', 'WebSocket live push', 5, ['I']),
    ('L', '3.5', 'Frontend dashboard (React)', 20, ['F', 'J']),
    ('M', '3.6', 'Software discovery & search', 6, ['H', 'J']),
    ('N', '3.7', 'Timetable & lab state', 6, ['J']),
    ('O', '3.8', 'Damage reports & maintenance', 6, ['I', 'J']),
    ('P', '4.1', 'Integration: agent - server - dashboard', 12, ['H', 'K', 'L']),
    ('Q', '4.2', 'E2E testbed & automated test suite', 7, ['P', 'M', 'N', 'O']),
    ('R', '4.3', 'Testing on real Ubuntu lab PCs', 7, ['Q']),
    ('S', '4.4', 'Fix issues found in lab testing', 8, ['R']),
    ('T', '5.1', 'Deploy to lab (systemd agents, server)', 4, ['S']),
    ('W', '5.2', 'Pilot run with students (UAT)', 7, ['T']),
    ('U', '5.3', 'Project report & documentation', 12, ['Q']),
    ('V', '5.4', 'Demo rehearsal & viva preparation', 5, ['W', 'U']),
]

CRIT_FILL, CRIT_LINE = '#F9D6D5', '#C0392B'
NORM_FILL, NORM_LINE = '#FFFFFF', '#3A6EA5'
OUT = Path(__file__).resolve().parent


def cpm(tasks):
    """Forward and backward pass. Returns {id: dict(es, ef, ls, lf, slack)}."""
    by_id = {t[0]: t for t in tasks}
    order, seen = [], set()

    def visit(tid):  # topological order, predecessors first
        if tid in seen:
            return
        for p in by_id[tid][4]:
            visit(p)
        seen.add(tid)
        order.append(tid)

    for t in tasks:
        visit(t[0])

    r = {tid: {} for tid in order}
    for tid in order:
        es = max((r[p]['ef'] for p in by_id[tid][4]), default=0)
        r[tid].update(es=es, ef=es + by_id[tid][3])
    finish = max(v['ef'] for v in r.values())

    successors = {tid: [s for s in order if tid in by_id[s][4]] for tid in order}
    for tid in reversed(order):
        lf = min((r[s]['ls'] for s in successors[tid]), default=finish)
        r[tid].update(lf=lf, ls=lf - by_id[tid][3])
        r[tid]['slack'] = r[tid]['ls'] - r[tid]['es']
    return r, finish, order, successors


def day(offset: int) -> date:
    return START + timedelta(days=offset)


def fmt(d: date) -> str:
    return d.strftime('%d %b')


def critical_path(r, order, by_id):
    """Follow zero-slack tasks from start to finish."""
    path = []
    current = next(t for t in order if r[t]['slack'] == 0 and r[t]['es'] == 0)
    while current:
        path.append(current)
        nxt = [s for s in order if current in by_id[s][4]
               and r[s]['slack'] == 0 and r[s]['es'] == r[current]['ef']]
        current = nxt[0] if nxt else None
    return path


def write_wbs(tasks):
    lines = ['@startwbs exp7-wbs', "' Generated by exp7_schedule.py - edit TASKS there, not here.",
             f'title {PROJECT} - Work Breakdown Structure', '',
             '<style>', 'wbsDiagram {', '  node { BackGroundColor #FFFFFF; LineColor #3A6EA5 }',
             '  :depth(0) { BackGroundColor #3A6EA5; FontColor #FFFFFF }',
             '  :depth(1) { BackGroundColor #EEF2F7 }', '}', '</style>', '',
             f'* 0 {PROJECT}']
    for code, name in PHASES:
        lines.append(f'** {code} {name}')
        for tid, wbs, title, dur, _ in tasks:
            if wbs.split('.')[0] == code:
                lines.append(f'*** {wbs} {title}\\n<size:10>Task {tid} - {dur} days</size>')
    lines.append('@endwbs')
    (OUT / 'exp7-wbs.puml').write_text('\n'.join(lines) + '\n')


def write_network(tasks, r, finish, crit_edges):
    by_id = {t[0]: t for t in tasks}
    lines = ['@startuml exp7-activity-network',
             "' Generated by exp7_schedule.py - edit TASKS there, not here.",
             f'title {PROJECT} - Activity Network (activity on node, durations in days)',
             'left to right direction', 'skinparam shadowing false',
             'skinparam defaultTextAlignment center', 'skinparam nodesep 25',
             'skinparam ranksep 45', 'skinparam ArrowColor #52606D', '',
             "' Node layout:  ES | Duration | EF  /  task  /  LS | Slack | LF", '']
    lines.append('circle "Start" as START')
    lines.append(f'circle "Finish\\nday {finish}" as FINISH')
    for tid, _wbs, title, dur, _ in tasks:
        v = r[tid]
        crit = v['slack'] == 0
        fill, line = (CRIT_FILL, CRIT_LINE) if crit else (NORM_FILL, NORM_LINE)
        short = title if len(title) <= 28 else title[:26].rstrip() + '...'
        label = (f'<b>{tid}</b>  {short}\\n'
                 f'| ES {v["es"]} | D {dur} | EF {v["ef"]} |\\n'
                 f'| LS {v["ls"]} | S {v["slack"]} | LF {v["lf"]} |')
        # "#back:X;line:Y" (no '#' inside) is the form PlantUML accepts
        # under "left to right direction".
        lines.append(f'rectangle "{label}" as {tid} #back:{fill[1:]};line:{line[1:]}')
    lines.append('')
    for tid, *_rest, preds in tasks:
        for p in preds or ['START']:
            crit = (p, tid) in crit_edges or (p == 'START' and r[tid]['slack'] == 0)
            style = f'-[{CRIT_LINE},bold]->' if crit else '-->'
            lines.append(f'{p} {style} {tid}')
    ends = [t for t in by_id if not any(t in by_id[s][4] for s in by_id)]
    for t in ends:
        style = f'-[{CRIT_LINE},bold]->' if r[t]['slack'] == 0 else '-->'
        lines.append(f'{t} {style} FINISH')
    lines += ['', 'legend right',
              f'  <back:{CRIT_FILL}>   </back> critical task (slack 0)   '
              f'<color:{CRIT_LINE}><b>--></b></color> critical path',
              '  ES/EF = earliest start/finish, LS/LF = latest start/finish, S = slack (days)',
              'endlegend', '@enduml']
    (OUT / 'exp7-activity-network.puml').write_text('\n'.join(lines) + '\n')


def write_gantt(tasks, r, finish, milestone):
    lines = ['@startgantt exp7-gantt', "' Generated by exp7_schedule.py - edit TASKS there, not here.",
             f'title {PROJECT} - Gantt Chart', 'printscale weekly zoom 2', 'hide footbox',
             f'Project starts {START.isoformat()}',
             f'today is {TODAY.isoformat()} and is colored in #FFE8A3', '']
    for code, name in PHASES:
        lines.append(f'-- {code} {name} --')
        for tid, wbs, title, dur, _ in tasks:
            if wbs.split('.')[0] != code:
                continue
            v = r[tid]
            lines.append(f'[{tid}. {title}] as [{tid}] starts {day(v["es"]).isoformat()} and lasts {dur} days')
            if v['slack'] == 0:
                lines.append(f'[{tid}] is colored in {CRIT_FILL}/{CRIT_LINE}')
            end = day(v['ef'] - 1)
            if end < TODAY:
                lines.append(f'[{tid}] is 100% completed')
            elif day(v['es']) < TODAY:
                pct = round(100 * (TODAY - day(v['es'])).days / dur)
                lines.append(f'[{tid}] is {pct}% completed')
    lines.append('')
    for tid, *_rest, preds in tasks:
        for p in preds:
            lines.append(f'[{p}] -> [{tid}]')
    # EF is exclusive, so the last working day is finish - 1.
    lines += ['', f'[{milestone}] happens {day(finish - 1).isoformat()}', '@endgantt']
    (OUT / 'exp7-gantt.puml').write_text('\n'.join(lines) + '\n')


def write_table(tasks, r, finish, path):
    rows = ['| Task | WBS | Activity | Predecessors | Duration (d) | ES | EF | LS | LF | Slack | Start | End |',
            '|---|---|---|---|---:|---:|---:|---:|---:|---:|---|---|']
    for tid, wbs, title, dur, preds in tasks:
        v = r[tid]
        name = f'**{title}**' if v['slack'] == 0 else title
        rows.append(f'| {tid} | {wbs} | {name} | {", ".join(preds) or "-"} | {dur} | {v["es"]} | '
                    f'{v["ef"]} | {v["ls"]} | {v["lf"]} | {v["slack"]} | '
                    f'{fmt(day(v["es"]))} | {fmt(day(v["ef"] - 1))} |')
    md = ['# Experiment 7 - CPM table', '',
          '_Generated by `exp7_schedule.py`; edit the TASKS list there and re-run._', '',
          f'Project start: **{START:%d %b %Y}** (day 0). Durations are in calendar days; '
          'EF and LF are exclusive day numbers, so a task with ES 0 and EF 3 occupies days 0-2.', '',
          *rows, '',
          f'**Critical path:** {" -> ".join(path)}  ',
          f'**Project duration:** {finish} days ({fmt(START)} to {fmt(day(finish - 1))} {day(finish - 1).year}).  ',
          'Critical activities (slack 0) are in bold; any delay to them delays the whole project.']
    (OUT / 'exp7-cpm-table.md').write_text('\n'.join(md) + '\n')


def main():
    r, finish, order, _succ = cpm(TASKS)
    by_id = {t[0]: t for t in TASKS}
    path = critical_path(r, order, by_id)
    crit_edges = set(zip(path, path[1:]))
    write_wbs(TASKS)
    write_network(TASKS, r, finish, crit_edges)
    write_gantt(TASKS, r, finish, 'Final demo & viva')
    write_table(TASKS, r, finish, path)
    print(f'critical path: {" -> ".join(path)}; duration {finish} days, '
          f'finish {day(finish - 1):%d %b %Y}')
    for tid in order:
        v = r[tid]
        print(f'  {tid}: ES {v["es"]:3} EF {v["ef"]:3} LS {v["ls"]:3} LF {v["lf"]:3} '
              f'slack {v["slack"]:2}  {fmt(day(v["es"]))} - {fmt(day(v["ef"] - 1))}')


if __name__ == '__main__':
    main()
